create table
  public.objects (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text null,
    description text null,
    thumbnail_url text null,
    lat decimal(10,8) null,
    lng decimal(11,8) null,
    constraint objects_pkey primary key (id)
  );

-- Add Row Level Security (RLS)
alter table public.objects enable row level security;

-- Create policies for authenticated users
create policy "Users can view all objects" on public.objects
    for select using (auth.role() = 'authenticated');

create policy "Users can insert new objects" on public.objects
    for insert with check (auth.role() = 'authenticated');

create policy "Users can update any object" on public.objects
    for update using (auth.role() = 'authenticated');

create policy "Users can delete any object" on public.objects
    for delete using (auth.role() = 'authenticated');

-- Grant necessary permissions
grant all on public.objects to authenticated;
grant all on public.objects to service_role;

-- Add comment for the thumbnail_url column
comment on column public.objects.thumbnail_url is 'URL to the object thumbnail image stored in Supabase storage';

-- Add comments for location columns
comment on column public.objects.lat is 'Latitude coordinate (-90 to 90 degrees)';
comment on column public.objects.lng is 'Longitude coordinate (-180 to 180 degrees)'; 